// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("simple-http-server")]
[assembly: AssemblyProductAttribute("Exira.SimpleHttpServer")]
[assembly: AssemblyDescriptionAttribute("Exira.SimpleHttpServer is a simple HTTP server to serve static files")]
[assembly: AssemblyVersionAttribute("1.0.0")]
[assembly: AssemblyFileVersionAttribute("1.0.0")]
[assembly: AssemblyMetadataAttribute("githash","7050749f52cdf528e72dc6c96034d89657b226be")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.0.0";
    }
}
