// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("simple-http-server")]
[assembly: AssemblyProductAttribute("Exira.SimpleHttpServer")]
[assembly: AssemblyDescriptionAttribute("Exira.SimpleHttpServer is a simple HTTP server to serve static files")]
[assembly: AssemblyVersionAttribute("1.0.0")]
[assembly: AssemblyFileVersionAttribute("1.0.0")]
[assembly: AssemblyMetadataAttribute("githash","8a283f55790eecde73bd79a140f73c3133c421f8")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.0.0";
    }
}
